version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: queries_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data:/var/lib/postgresql/data

